# Generated by Django 5.1 on 2024-08-31 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_grammarmaterial_alter_consultationrequest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название раздела')),
                ('description', models.TextField(blank=True, verbose_name='Описание раздела')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Раздел грамматики',
                'verbose_name_plural': 'Разделы грамматики',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AlterModelOptions(
            name='grammarmaterial',
            options={'ordering': ['section', 'order', 'title'], 'verbose_name': 'Грамматический материал', 'verbose_name_plural': 'Грамматические материалы'},
        ),
        migrations.AddField(
            model_name='grammarmaterial',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AddField(
            model_name='grammarmaterial',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='myapp.grammarsection', verbose_name='Раздел'),
            preserve_default=False,
        ),
    ]
